name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: arc
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: pre-commit
        uses: pre-commit/action@v3.0.1

  deploy:
    runs-on: arc
    needs: [lint]
    env:
      SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      ANSIBLE_VAULT_PASSWORD_FILE: ./scripts/vault.bash
      ANSIBLE_LOCALHOST_WARNING: "false"
      ANSIBLE_INVENTORY_UNPARSED_WARNING: "false"
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup sops
        uses: mdgreenwald/mozilla-sops-action@v1

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: install ansible
        run: pip install ansible

      - name: dependencies
        run: ansible-galaxy collection install -r requirements.yml

      - name: deploy
        run: ansible-playbook .setup_project.yml
